name: Terraform CI/CD (Prod)

on:
  push:
    branches:
      - main
    paths:
      - '**/*.tf'
      - '.github/workflows/terraform.yml'

permissions:
  contents: read
  id-token: write

env:
  TF_WORKING_DIR: .

jobs:
  validate-plan:
    name: Terraform Validate & Plan (main)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-session-name: terraform-ci
        

      - name: Terraform Format
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform fmt -check -diff

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init -input=false

      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate

      - name: Terraform Import subnet group
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform import aws_db_subnet_group.rds rds-default-subnet-group
        continue-on-error: true
        
      - name: Terraform Import parameter group
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform import aws_db_parameter_group.postgres mecanica-xpto-postgres-17-params
        continue-on-error: true

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -input=false -no-color

  apply:
    name: Terraform Apply (prod)
    runs-on: ubuntu-latest
    needs: validate-plan
    if: ${{ github.ref == 'refs/heads/main' }}

    environment:
      name: production
      url: https://console.aws.amazon.com/rds/home?region=us-east-1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-session-name: terraform-apply

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init -input=false

      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve -input=false
